all: q1_1 q1_2 q1_3

q1_1: Q1-1_brute_force_knapsack.c
	gcc -o Q1-1_brute_force_knapsack.out Q1-1_brute_force_knapsack.c

q1_2: Q1-2_greedy_algorithm.c
	gcc -o Q1-2_greedy_algorithm.out Q1-2_greedy_algorithm.c

q1_3: Q1-3_dynamic_programming_knapsack.c
	gcc -o Q1-3_dynamic_programming_knapsack.out Q1-3_dynamic_programming_knapsack.c

clean:
	rm -f Q1-1_brute_force_knapsack.out Q1-2_greedy_algorithm.out Q1-3_dynamic_programming_knapsack.out